### ISSUE TITLE
PHP 8.4 support

### ISSUE THREAD

**Issue by vinkla** [olssonm/swish-php#15]
PHP 8.4 has deprecated the implicit marking of parameters as nullable. We should adjust our code and test it against PHP 8.4. I will create a pull request as soon as possible to address this issue.

```
Deprecated: Olssonm\Swish\Client::setup(): Implicitly marking parameter $client as nullable is deprecated, the explicit nullable type must be used instead in /vendor/olssonm/swish-php/src/Client.php on line 46
```

**Comment by olssonm** [comment]
Thanks! Yeah, I'm aware of the issue. Haven't been able to update my own environments to PHP 8.4 just yet though.

Feel free to submit a PR, else I should have a fix in place in a couple of days. 

We should use the "`?string`"-syntax to indicate a nullable type.

**Comment by olssonm** [comment]
@vinkla v3.1 is now available that fixes the issues with implicitly nullable parameters in PHP 8.4 😀
